name: Chaos
version: ${project.version}
main: com.themythichunter.chaos.Chaos
api-version: 1.19
description: Fun with random Minecraft events.
author: MythicHunter758
commands:
  chaos:
    description: Chaos base command.
permissions:
  chaos.use:
    description: Able to use all the commands in the chaos plugin.