name: Chaos
version: ${project.version}
main: com.netlify.hparcells.chaos.Chaos
api-version: 1.16
description: Fun with random Minecraft events.
author: MythicHunter758
commands:
  chaos:
    description: Chaos base command.
    usage: /chaos [action]
    permission: chaos.use
    permission-message: You don't have <permission>